# Site settings
title: Ndarray Data Language
email: aleksandar.jelenak@gmail.com
description: Simple language with clean syntax for describing the content of multidimensional array (ndarray, datacube) data files.

baseurl: "/ndl"
url: https://ajelenak.github.io/ndl
git_address: https://github.com/ajelenak/ndl
git_edit_address: https://github.com/ajelenak/ndl/tree/master/docs

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: yeti

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
  - docker-compose.yml
timezone: America/New York
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      sectionid: blog

  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
      sectionid: docs
      seo:
        type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
